version: '3.9'

services:
  skc-api:
    image: "openjdk:17.0-jdk-slim"
    ports:
      - "9998:8443"
    volumes:
       - ./build/libs/skc-api.jar:/skc-api.jar
    command: java -jar skc-api.jar
    restart: always
    deploy:
      resources:
        limits:
          memory: 600M
    networks:
      - skc-network
    environment:
      - SSL_KEYSTORE_PASSWORD=${SSL_KEYSTORE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - SPRING_PROFILES_ACTIVE=docker-local

networks:
  skc-network:
    name: skc-network
    driver: bridge
