services:
  skc-api:
    image: "eclipse-temurin:25-jre-alpine"
    ports:
      - "4443:8443"
    volumes:
      - ./build/libs/skc-api.jar:/skc-api.jar
    command: java -jar skc-api.jar
    restart: always
    deploy:
      resources:
        limits:
          memory: 500M
    networks:
      - skc
    environment:
      - SSL_KEYSTORE_PASSWORD=${SSL_KEYSTORE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - SPRING_PROFILES_ACTIVE=docker,prod
      - SKC_SUGGESTION_ENGINE_API_KEY=${SKC_SUGGESTION_ENGINE_API_KEY}
    labels:
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances: '[{"host":"%%host%%", "port": "%%port%%"}]'
      com.datadoghq.ad.logs: >-
        [{
          "source": "java", 
          "service": "skc-api",
          "auto_multi_line_detection": true,
          "log_processing_rules": [{
            "type": "exclude_at_match",
            "name": "exclude_health_check",
            "pattern" : "/api/v1/status"
          }]
        }]
      com.datadoghq.tags.env: 'prod'
      com.datadoghq.tags.service: 'skc-api'

networks:
  skc:
    name: skc
    driver: bridge
    external: true # network was already created, if you need to recreate the network - make this false