version: '3.9'

services:
  skc-api:
    image: "eclipse-temurin:21.0.1_12-jre-alpine"
    ports:
      - "9998:8443"
    volumes:
      - ./build/libs/skc-api.jar:/skc-api.jar
    command: java -jar skc-api.jar
    restart: always
    deploy:
      resources:
        limits:
          memory: 700M
    networks:
      - skc-network
    environment:
      - SSL_KEYSTORE_PASSWORD=${SSL_KEYSTORE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - SPRING_PROFILES_ACTIVE=docker-local
      - SKC_SUGGESTION_ENGINE_API_KEY=${SKC_SUGGESTION_ENGINE_API_KEY}

networks:
  skc-network:
    name: skc-network
    driver: bridge
