version: '3'

services:
  ygo-api:
    image: "openjdk:11.0-jdk-slim"
    ports:
      - "4443-4444:8443"
    volumes:
       - ./build/libs/ygo-api.jar:/ygo-api.jar
    command: java -jar ygo-api.jar
    restart: always
    networks:
      - yugioh-api
    environment:
      - SSL_KEYSTORE_PASSWORD=${SSL_KEYSTORE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - SPRING_PROFILES_ACTIVE=docker-remote
    scale: 2

networks:
  yugioh-api:
    name: yugioh-api
    driver: bridge