spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yugioh_API_DB
    username: root
    password:
    tomcat:
      initial-size: 15
      max-wait: 20000
      max-active: 50
      max-idle: 15
      min-idle: 8
      default-auto-commit: true
  profiles:
    active: production

server:
  port: 9999