
ygo:
  endpoints:
    v1:
      test-call: /api/v1/testcall
      ban-list-dates: /api/v1/ban/dates
      ban-list-new-cards: /api/v1/ban/new
      ban-list-removed-cards: /api/v1/ban/removed
      banned-cards: /api/v1/ban/cards
      card: /api/v1/card

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yugioh_API_DB
    username: root
    password:

server:
  port: 9999