spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yugioh_API_DB
    username: root
    password:
  hateoas:
    use-hal-as-default-json-media-type: true

server:
  port: 9999
  servlet:
    contextPath: /api/v1
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 4096
  http2:
    enabled: true