spring:
  datasource:
    hikari:
      maximum-pool-size: 30
    url: jdbc:mysql://ygo-db:3306/yugioh_API_DB
    username: root
    password: ${MYSQL_ROOT_PASSWORD}
  hateoas:
    use-hal-as-default-json-media-type: true

server:
  port: 8443
  servlet:
    contextPath: /api/v1
  ssl:
    key-store: classpath:ygo-api-keystore.jks
    key-store-password: ${SSL_KEYSTORE_PASSWORD}
    key-alias: ygoapi
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 16384
  http2:
    enabled: true