
ygo:
  endpoints:
    v1:
      test-call: /api/v1/testcall
      ban-list-dates: /api/v1/ban/dates
      ban-list-new-cards: /api/v1/ban/new
      ban-list-removed-cards: /api/v1/ban/removed

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yugioh_API_DB
    username: root
    password:
  hateoas:
    use-hal-as-default-json-media-type: true

server:
  port: 9999
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 4096
  http2:
    enabled: true