spring:
  datasource:
    hikari:
      maximumPoolSize: 30
      minimumIdle: 10
    # using custom timezone for this API, so connection url needs these serverTimezone, useLegacyDatetimeCode and cacheDefaultTimezone set else dates will be off if API TZ is behind DB TZ  - more info here https://stackoverflow.com/questions/47228265/spring-jpa-hibernate-mysql-localdate-off-one-day-after-persist
    url: jdbc:mysql://localhost:3306/skc_api_db?serverTimezone=${user.timezone}&useLegacyDatetimeCode=false&cacheDefaultTimezone=false
    username: root
    password:
  jpa:
    open-in-view: false
  hateoas:
    use-hal-as-default-json-media-type: true
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher # fixes spring-fox error on spring-boot >= v2.6

server:
  port: 9999
  servlet:
    contextPath: /api/v1
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 4096
  http2:
    enabled: true

springdoc:
  packagesToScan: com.rtomyj.skc
  pathsToMatch: /**

api:
  skc-suggestion-engine:
    base-uri: http://localhost:90
    key: ${SKC_SUGGESTION_ENGINE_API_KEY}
    status-endpoint: /api/v1/suggestions/status
    traffic-endpoint: /api/v1/suggestions/traffic-analysis

---
spring:
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
  config:
    activate.on-profile: docker-local
  datasource:
    # using custom timezone for this API, so connection url needs these serverTimezone, useLegacyDatetimeCode and cacheDefaultTimezone set else dates will be off if API TZ is behind DB TZ  - more info here https://stackoverflow.com/questions/47228265/spring-jpa-hibernate-mysql-localdate-off-one-day-after-persist
    url: jdbc:mysql://skc-api-db:3306/skc_api_db?serverTimezone=${user.timezone}&useLegacyDatetimeCode=false&cacheDefaultTimezone=false
    username: root
    password: ${MYSQL_ROOT_PASSWORD}

server:
  port: 8443
  ssl:
    key-store: classpath:skc-api.jks
    key-store-password: ${SSL_KEYSTORE_PASSWORD}
    key-alias: skcapi

api:
  skc-suggestion-engine:
    base-uri: https://suggestions.skc-ygo-api.com
---
spring:
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
  config:
    activate.on-profile: docker-remote
  datasource:
    # using custom timezone for this API, so connection url needs these serverTimezone, useLegacyDatetimeCode and cacheDefaultTimezone set else dates will be off if API TZ is behind DB TZ  - more info here https://stackoverflow.com/questions/47228265/spring-jpa-hibernate-mysql-localdate-off-one-day-after-persist
    url: jdbc:mysql://skc-api-db/skc_api_db?serverTimezone=${user.timezone}&useLegacyDatetimeCode=false&cacheDefaultTimezone=false
    username: root
    password: ${MYSQL_ROOT_PASSWORD}

server:
  port: 8443
  ssl:
    key-store: classpath:skc-api.jks
    key-store-password: ${SSL_KEYSTORE_PASSWORD}
    key-alias: skcapi

api:
  skc-suggestion-engine:
    base-uri: https://suggestions.skc-ygo-api.com