spring:
  datasource:
    hikari:
      maximum-pool-size: 30
    url: jdbc:mysql://localhost:3306/skc_api_db
    username: root
    password:
  hateoas:
    use-hal-as-default-json-media-type: true
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher # fixes spring-fox error on spring-boot >= v2.6

server:
  port: 9999
  servlet:
    contextPath: /api/v1
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 16384
  http2:
    enabled: true


---
spring:
  profiles: docker-local
  datasource:
    url: jdbc:mysql://skc-api-db:3306/skc_api_db
    username: root
    password: ${MYSQL_ROOT_PASSWORD}

server:
  port: 8443
  ssl:
    key-store: classpath:skc-api-keystore.jks
    key-store-password: ${SSL_KEYSTORE_PASSWORD}
    key-alias: ygoapi

---
spring:
  profiles: docker-remote
  datasource:
    url: jdbc:mysql://skc-api-db:3306/skc_api_db
    username: root
    password: ${MYSQL_ROOT_PASSWORD}

server:
  port: 8443
  ssl:
    key-store: classpath:skc-api-keystore.jks
    key-store-password: ${SSL_KEYSTORE_PASSWORD}
    key-alias: ygoapi