spring:
  datasource:
    hikari:
      maximum-pool-size: 30
    url: jdbc:mysql://localhost:3306/skc_api_db
    username: root
    password:
  jpa:
    open-in-view: false
  hateoas:
    use-hal-as-default-json-media-type: true
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher # fixes spring-fox error on spring-boot >= v2.6

server:
  port: 9999
  servlet:
    contextPath: /api/v1
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 4096
  http2:
    enabled: true

springdoc:
  packagesToScan: com.rtomyj.skc
  pathsToMatch: /**

api:
  skcSuggestionEngine:
    uri: http://localhost:9000
    endpoints:
      status: /api/v1/suggestions/status
      traffic: /api/v1/suggestions/traffic-analysis
    key: ${SKC_SUGGESTION_ENGINE_API_KEY}

---
spring:
  config:
    activate.on-profile: docker-local
  datasource:
    url: jdbc:mysql://skc-api-db:3306/skc_api_db
    username: root
    password: ${MYSQL_ROOT_PASSWORD}

server:
  port: 8443
  ssl:
    key-store: classpath:skc-api.jks
    key-store-password: ${SSL_KEYSTORE_PASSWORD}
    key-alias: skcapi

api:
  skcSuggestionEngine:
    uri: https://skc-suggestion-engine:9000
---
spring:
  config:
    activate.on-profile: docker-remote
  datasource:
    url: jdbc:mysql://skc-api-db:3306/skc_api_db
    username: root
    password: ${MYSQL_ROOT_PASSWORD}

server:
  port: 8443
  ssl:
    key-store: classpath:skc-api.jks
    key-store-password: ${SSL_KEYSTORE_PASSWORD}
    key-alias: skcapi

api:
  skcSuggestionEngine:
    uri: https://skc-suggestion-engine:9000