spring:
  datasource:
    url: jdbc:mysql://ygo-db:3306/yugioh_API_DB
    username: root
    password: ${MYSQL_ROOT_PASSWORD}
  hateoas:
    use-hal-as-default-json-media-type: true

server:
  port: 8080
  servlet:
    contextPath: /api/v1
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 16384
  http2:
    enabled: true