spring:
  webflux:
    base-path: /api/v1
  main:
    web-application-type: reactive
  datasource:
    hikari:
      maximumPoolSize: 30
      minimumIdle: 10
    # using custom timezone for this API, so connection url needs these serverTimezone, useLegacyDatetimeCode and cacheDefaultTimezone set else dates will be off if API TZ is behind DB TZ  - more info here https://stackoverflow.com/questions/47228265/spring-jpa-hibernate-mysql-localdate-off-one-day-after-persist
    url: jdbc:mariadb://localhost:3306/skc_api_db?serverTimezone=${user.timezone}&useLegacyDatetimeCode=false&cacheDefaultTimezone=false
    username: root
    password:
  jpa:
    open-in-view: false
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher # fixes spring-fox error on spring-boot >= v2.6

server:
  port: 9999
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 1024
  http2:
    enabled: true

# https://springdoc.org/properties.html
springdoc:
  packagesToScan: com.rtomyj.skc
  pathsToMatch: /**
  remove-broken-reference-definitions: false
  enable-kotlin: true
  api-docs:
    version: OPENAPI_3_1

api:
  skc-suggestion-engine:
    cert-hostname: suggestions.skc-ygo-api.com
    base-uri: https://localhost:9000
    key: ${SKC_SUGGESTION_ENGINE_API_KEY}
    status-endpoint: /api/v1/suggestions/status
    traffic-endpoint: /api/v1/suggestions/traffic-analysis
---
spring:
  config:
    activate.on-profile: docker
  datasource:
    # using custom timezone for this API, so connection url needs these serverTimezone, useLegacyDatetimeCode and cacheDefaultTimezone set else dates will be off if API TZ is behind DB TZ  - more info here https://stackoverflow.com/questions/47228265/spring-jpa-hibernate-mysql-localdate-off-one-day-after-persist
    url: jdbc:mariadb://skc-api-db/skc_api_db?serverTimezone=${user.timezone}&useLegacyDatetimeCode=false&cacheDefaultTimezone=false
    username: root
    password: ${MYSQL_ROOT_PASSWORD}

server:
  ssl:
    key-store: classpath:skc-api.jks
    key-store-password: ${SSL_KEYSTORE_PASSWORD}
    key-alias: skcapi

api:
  skc-suggestion-engine:
    base-uri: https://skc-suggestion-engine:9000
---
spring:
  config:
    activate.on-profile: prod

server:
  port: 8443
---
spring:
  config:
    activate.on-profile: dev

server:
  port: 8450