mysql -u root < "cards.sql"

mysql -u root < "cards_normal.sql"
mysql -u root < "cards_effect.sql"
mysql -u root < "cards_ritual.sql"
mysql -u root < "cards_fusion.sql"
mysql -u root < "cards_synchro.sql"
mysql -u root < "cards_xyz.sql"
mysql -u root < "cards_normal_pendulum.sql"
mysql -u root < "cards_effect_pendulum.sql"
mysql -u root < "cards_link.sql"
mysql -u root < "cards_spell.sql"
mysql -u root < "cards_trap.sql"

mysql -u root < "ban_list.sql"