name: Java CI

on:
  push:
    branches:
      - release
      - master
      - 2.1.7
    tags:
      - v**
  pull_request:
    types:
      - opened
      - edited
      - reopened

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build & Unit Test
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper
          arguments: build
