name: Build & JUnits

on:
  push:
    branches:
      - release
      - master
    tags:
      - v**
  pull_request:
    types:
      - opened
      - edited
      - reopened

jobs:
  build-and-junits:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4

      - name: Set up JDK
        uses: actions/setup-java@v3.12.0
        with:
          java-version: '20'
          distribution: 'temurin'

      - name: Execute Gradle Build
        uses: gradle/gradle-build-action@v2.8.1
        with:
          gradle-version: wrapper
          arguments: build

      - name: Upload Results
        uses: actions/upload-artifact@v3.1.3
        with:
          name: junit-results
          path: build/reports/tests/test